### ISSUE TITLE
Can we configure dependabot to achieve our goals?

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3049]
The following dependabot config attempted to apply the maintenance label to new PRs that it opened.  However, with this config, it didn't open any PRs, security-related or not.

It would be helpful if we can configure dependabot's security update PRs to come in with the maintenance label, but leave all the other dependabot settings as their defaults.

Old .github/dependabot.yml:
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
      - "maintenance"
    # Only create PRs for security updates
    open-pull-requests-limit: 0
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    # Only create PRs for security updates
    open-pull-requests-limit: 0
    labels:
      - "ruby"
      - "dependencies"
      - "maintenance"
```
